export interface MagicSpell {
  id: number;
  name: string;
  hpBonusModifier: number;
}

const magicSpells: MagicSpell[] = [
  {id: 0, name: 'None', hpBonusModifier: 0},
  {id: 1, name: 'Fire', hpBonusModifier: 1},
  {id: 2, name: 'Fira', hpBonusModifier: 2},
  {id: 3, name: 'Firaga', hpBonusModifier: 14},
  {id: 4, name: 'Blizzard', hpBonusModifier: 1},
  {id: 5, name: 'Blizzara', hpBonusModifier: 2},
  {id: 6, name: 'Blizzaga', hpBonusModifier: 14},
  {id: 7, name: 'Thunder', hpBonusModifier: 1},
  {id: 8, name: 'Thundara', hpBonusModifier: 2},
  {id: 9, name: 'Thundaga', hpBonusModifier: 14},
  {id: 10, name: 'Water', hpBonusModifier: 3},
  {id: 11, name: 'Aero', hpBonusModifier: 3},
  {id: 12, name: 'Bio', hpBonusModifier: 7},
  {id: 13, name: 'Demi', hpBonusModifier: 16},
  {id: 14, name: 'Holy', hpBonusModifier: 38},
  {id: 15, name: 'Flare', hpBonusModifier: 32},
  {id: 16, name: 'Meteor', hpBonusModifier: 46},
  {id: 17, name: 'Quake', hpBonusModifier: 26},
  {id: 18, name: 'Tornado', hpBonusModifier: 30},
  {id: 19, name: 'Ultima', hpBonusModifier: 60},
  {id: 20, name: 'Apocalypse', hpBonusModifier: 42},
  {id: 21, name: 'Cure', hpBonusModifier: 2},
  {id: 22, name: 'Cura', hpBonusModifier: 5},
  {id: 23, name: 'Curaga', hpBonusModifier: 22},
  {id: 24, name: 'Life', hpBonusModifier: 12},
  {id: 25, name: 'Full-Life', hpBonusModifier: 48},
  {id: 26, name: 'Regen', hpBonusModifier: 26},
  {id: 27, name: 'Esuna', hpBonusModifier: 5},
  {id: 28, name: 'Dispel', hpBonusModifier: 10},
  {id: 29, name: 'Protect', hpBonusModifier: 4},
  {id: 30, name: 'Shell', hpBonusModifier: 4},
  {id: 31, name: 'Reflect', hpBonusModifier: 20},
  {id: 32, name: 'Aura', hpBonusModifier: 34},
  {id: 33, name: 'Double', hpBonusModifier: 2},
  {id: 34, name: 'Triple', hpBonusModifier: 24},
  {id: 35, name: 'Haste', hpBonusModifier: 5},
  {id: 36, name: 'Slow', hpBonusModifier: 5},
  {id: 37, name: 'Stop', hpBonusModifier: 8},
  {id: 38, name: 'Blind', hpBonusModifier: 1},
  {id: 39, name: 'Confuse', hpBonusModifier: 7},
  {id: 40, name: 'Sleep', hpBonusModifier: 1},
  {id: 41, name: 'Silence', hpBonusModifier: 1},
  {id: 42, name: 'Break', hpBonusModifier: 10},
  {id: 43, name: 'Death', hpBonusModifier: 18},
  {id: 44, name: 'Drain', hpBonusModifier: 4},
  {id: 45, name: 'Pain', hpBonusModifier: 28},
  {id: 46, name: 'Berserk', hpBonusModifier: 3},
  {id: 47, name: 'Float', hpBonusModifier: 2},
  {id: 48, name: 'Zombie', hpBonusModifier: 8},
  {id: 49, name: 'Meltdown', hpBonusModifier: 15},
  {id: 50, name: 'Scan', hpBonusModifier: 1},
  {id: 51, name: 'Full-Cure', hpBonusModifier: 0},
  {id: 52, name: 'Wall', hpBonusModifier: 0},
  {id: 53, name: 'Rapture', hpBonusModifier: 0},
  {id: 54, name: 'Percent', hpBonusModifier: 0},
  {id: 55, name: 'Catastrophe', hpBonusModifier: 0},
  {id: 56, name: 'The End', hpBonusModifier: 0},
];

export default magicSpells;
